import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  de: {
    // Navigation
    'nav.services': 'Services',
    'nav.media': 'Media',
    'nav.studio': 'Studio',
    'nav.lab': 'Lab',
    'nav.home': 'Home',
    'nav.contact': 'Kontakt',
    'nav.contactAction': 'Kontakt aufnehmen',
    
    // Common
    'common.learnMore': 'Mehr erfahren',
    'common.getStarted': 'Loslegen',
    'common.contact': 'Kontakt',
    'common.backToHome': 'Zurück zur Startseite',
    'common.discussProject': 'Projekt besprechen',
    'common.startProject': 'Projekt starten',
    'common.exploreServices': 'Services erkunden',
    'common.requestProject': 'Projekt anfragen',
    'common.designProject': 'Design-Projekt starten',
    'common.readyForNext': 'Bereit für den nächsten Schritt?',
    'common.readyForFuture': 'Bereit für die Zukunft?',
    'common.readyForDesign': 'Let´s design the edge',
    'common.readyForProject': 'Bereit für Ihr nächstes Projekt?',
    'common.readyForMedia': 'Bereit für Ihre Medienproduktion?',
    'common.in48Hours': 'In 48 Stunden',
    'common.available': 'VERFÜGBAR',
    'common.coming': 'Q4 2025',
    'common.ourServices': 'UNSERE LEISTUNGEN',
    'common.keyActivities': 'Key Activities',
    'common.projectServices': 'PROJEKTBASIERTE LEISTUNGEN',
    'common.kiPowered': 'KI-POWERED SOLUTIONS',
    'common.featuredApps': 'Featured Applications',
    'common.upcomingApps': 'Upcoming Applications',
    'common.additionally': 'ZUSÄTZLICH',
    'common.inDevelopment': 'In aktiver Entwicklung',
    
    // Homepage
    'home.hero.brand': 'BRAND',
    'home.hero.intelligence': 'INTELLIGENCE',
    'home.hero.forDigitalAge': 'FOR THE DIGITAL AGE',
    'home.hero.title': 'New Edge',
    'home.hero.subtitle': 'Ein Team. Drei Ansätze. Unendliche Möglichkeiten.',
    'home.hero.description': 'Wir verwandeln Visionen in digitale Realitäten durch intelligente Strategien, überzeugende Inhalte und innovative Technologien.',
    'home.visual.strategy': 'STRATEGIE',
    'home.visual.onPoint': 'ON-POINT',
    'home.visual.creative': 'CREATIVE TECH',
    'home.mission.title': 'Innovation voranbringen durch intelligente Automatisierung',
    'home.mission.description': 'Mit Media, Studio und Lab verbinden wir Inhalte, Design und Systeme – für Marken, die funktionieren und wachsen.',
    'home.grow.title': 'Wir wachsen mit unseren Kunden',
    'home.mission.card.title': 'UNSERE MISSION',
    'home.mission.card.description': 'Mit Media, Studio und Lab verbinden wir Inhalte, Design und Systeme - für Marken, die funktionieren und wachsen.',
    'home.vision.card.title': 'UNSERE VISION',
    'home.vision.card.description': 'Wir gestalten eine neue Generation von Marken: automatisiert, strukturiert und sichtbar.',
    'home.goal.card.title': 'UNSER ZIEL',
    'home.goal.card.description': 'Menschen und Unternehmen den Zugang zu Innovation bieten für einfachere und effektivere Abläufe.',
    'home.why.title': 'Warum New Edge?',
    'home.usp1.title': 'Impact durch Automatisierung',
    'home.usp1.description': 'Intelligente Systeme steigern Ihre Effizienz nachhaltig',
    'home.usp2.title': 'Marketingexpertise trifft technische Umsetzung',
    'home.usp2.description': 'Perfekte Symbiose aus Strategie und Innovation',
    'home.usp3.title': 'Fokus auf Innovation und Wachstum',
    'home.usp3.description': 'Zukunftsorientierte Lösungen für nachhaltigen Erfolg',
    'home.services.title': 'Unsere Services',
    'home.contact.title': 'Bereit durchzustarten?',
    'home.contact.description': 'Lassen Sie uns über Ihr nächstes Projekt sprechen und gemeinsam etwas Außergewöhnliches schaffen.',
    'home.contact.form.name': 'Name',
    'home.contact.form.email': 'E-Mail',
    'home.contact.form.message': 'Nachricht',
    'home.contact.form.send': 'Nachricht senden',
    'home.contact.success.title': 'Wir designen für dich',
    'home.contact.success.message': 'Vielen Dank für deine Anfrage! Wir melden uns bald bei dir.',
    'home.contact.error.title': 'Fehler',
    'home.contact.error.message': 'Es gab ein Problem beim Senden deiner Nachricht. Bitte versuche es erneut.',
    
    // Services
    'services.hero.title': 'NEW EDGE SERVICES',
    'services.hero.journey': 'THE JOURNEY',
    'services.hero.fromVision': 'FROM VISION TO REALITY',
    'services.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'services.hero.description': 'Wir begleiten Sie auf einer strukturierten Reise von der ersten Idee bis zur finalen Implementierung.',
    'services.keyActivities': 'Key Activities',
    'services.yourPath': 'Ihr Weg zum Erfolg',
    'services.strategy.title': 'Strategic Consulting',
    'services.strategy.description': 'Digitale Transformation und strategische Beratung für nachhaltige Geschäftserfolge.',
    'services.design.title': 'Creative Design',
    'services.design.description': 'Ästhetische Lösungen, die Ihre Marke zum Leben erwecken und Nutzer begeistern.',
    'services.development.title': 'Tech Development',
    'services.development.description': 'Modernste Technologielösungen für komplexe digitale Herausforderungen.',
    'services.studio.tag': 'NEW EDGE STUDIO',
    'services.studio.tagline': 'Ihre Ideen, unsere Strategie',
    'services.studio.description': 'Hier beginnt alles. Wir entwickeln die visuelle Identität, Strategie und das Fundament für Ihr Projekt.',
    'services.studio.button': 'Strategie entwickeln',
    'services.media.tag': 'NEW EDGE MEDIA',
    'services.media.tagline': 'Die perfekte Bühne für Ihre Marke',
    'services.media.description': 'Content-Produktion und Reichweite. Hier wird alles produziert, veröffentlicht und gesteuert.',
    'services.media.button': 'Content erstellen',
    'services.lab.tag': 'NEW EDGE LAB',
    'services.lab.tagline': 'Die perfekte Schnittstelle für Strategie & Technologie',
    'services.lab.description': 'Backend, KI und technische Umsetzung. Hier wird alles intelligent und automatisiert.',
    'services.lab.button': 'Technologie implementieren',
    'services.cta.title': 'Bereit für Ihr nächstes Projekt?',
    'services.cta.description': 'Lassen Sie uns gemeinsam innovative Lösungen entwickeln, die Ihr Unternehmen voranbringen.',
    
    // Media
    'media.hero.title': 'NEW EDGE MEDIA',
    'media.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'media.hero.revolution': 'CONTENT REVOLUTION',
    'media.hero.description': 'MEDIA produziert, veröffentlicht und steuert alles, was nach außen sichtbar wird.',
    'media.hero.tagline': ' Ab Strategie bis zur viralen Umsetzung.',
    'media.services.operative': 'Operative Umsetzung',
    'media.services.operative.desc': 'Strategische Content-Produktion und zielgerichtete Reichweite für maximale Sichtbarkeit.',
    'media.services.content': 'Content-Produktion & Reichweite',
    'media.services.content.desc': 'Professionelle Content-Erstellung für maximale Reichweite und Engagement.',
    'media.services.marketing': 'Marketing & Sichtbarkeit',
    'media.services.marketing.desc': 'Strategische Kampagnen für optimale Performance-Marketing und Launchkampagnen.',
    'media.services.launch': 'Launchkampagnen & Performance-Marketing',
    'media.services.launch.desc': 'Erfolgreiche Produktlaunches und datengetriebenes Performance-Marketing.',
    'media.services.seo': 'SEO/SEA-Umsetzung & Conversion-Tracking',
    'media.services.seo.desc': 'Suchmaschinenoptimierung und Content-Marketing mit präzisem Copywriting.',
    'media.services.copywriting': 'Content-Marketing & Copywriting',
    'media.services.copywriting.desc': 'Strategisches Content-Marketing mit überzeugenden Texten und Botschaften.',
    'media.services.creative': 'Creative Content Production (Video, Visuals, Reels)',
    'media.services.creative.desc': 'Hochwertige Video- und Visual-Produktion für alle digitalen Kanäle.',
    'media.services.newsletter': 'Newsletter, Ads & Kampagnenausspielung',
    'media.services.newsletter.desc': 'Professionelle Newsletter-Kampagnen und strategische Werbeanzeigen-Ausspielung.',
    'media.cta.title': 'Bereit für den nächsten Schritt?',
    'media.cta.description': 'Lassen Sie uns gemeinsam Ihre Content-Strategie revolutionieren und nachhaltige Reichweite aufbauen.',
    
    // Studio
    'studio.hero.title': 'NEW EDGE STUDIO',
    'studio.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'studio.hero.excellence': 'DESIGN EXCELLENCE',
    'studio.hero.description': 'STUDIO liefert das Fundament: Alles wird strategisch vorbereitet, durchdacht und geplant.',
    'studio.hero.tagline': ' Für eine reibungslose Umsetzung in MEDIA & LAB',
    'studio.services.foundations': 'Strategische Fundamente für Ihren Markenerfolg',
    'studio.services.strategy': 'Strategie & Markenidentität',
    'studio.services.strategy.desc': 'Strategische Markenpositionierung und Zielgruppenanalyse für eine klare Ausrichtung.',
    'studio.services.brand': 'Brand Story',
    'studio.services.brand.desc': 'Authentische Markenstories mit klaren Werten und einzigartiger Tonalität.',
    'studio.services.competition': 'Wettbewerbsanalyse & Differenzierungsstrategie',
    'studio.services.competition.desc': 'Strategische Marktanalyse und visuelles Konzept für klare Abgrenzung.',
    'studio.services.moodboards': 'Moodboards & Keyvisual-Richtung',
    'studio.services.moodboards.desc': 'Kreative Design- und Farbwelten für eine einheitliche visuelle Identität.',
    'studio.services.templates': 'Template-Rahmen für Social Media & Print',
    'studio.services.templates.desc': 'Einheitliche Vorlagen und digitale Struktur mit Funnel-Logik.',
    'studio.services.wireframes': 'Nutzerführung & Funnel-Wireframes',
    'studio.services.wireframes.desc': 'Conversion-Ziele und strategischer Seitenaufbau für maximale Effektivität.',
    'studio.cta.title': 'Let´s design the edge',
    'studio.cta.description': 'Gemeinsam entwickeln wir ein Design, das Ihre Vision zum Leben erweckt und Ihre Zielgruppe begeistert.',
    
    // Lab
    'lab.hero.title': 'NEW EDGE LAB',
    'lab.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'lab.hero.innovation': 'TECH INNOVATION',
    'lab.hero.description': 'LAB macht aus Ideen reale, funktionierende Systeme — sicher, automatisiert, effizient.',
    'lab.hero.tagline': '     Innovation durch intelligente Technologie.',
    'lab.services.tech': 'Technische Umsetzung',
    'lab.services.requirements': 'Maßgeschneiderte Lösungen für Ihre spezifischen Anforderungen',
    'lab.services.implementation': 'Technische Umsetzung',
    'lab.services.implementation.desc': 'Professionelle Entwicklung und Implementierung technischer Lösungen für Ihr Unternehmen.',
    'lab.services.ai': 'KI-Integration & Automation',
    'lab.services.ai.desc': 'Intelligente Automatisierung und KI-Integration in bestehende Geschäftsprozesse.',
    'lab.services.backend': 'Backend & Tech-Implementierung',
    'lab.services.backend.desc': 'Robuste Backend-Systeme und technische Infrastruktur für skalierbare Anwendungen.',
    'lab.services.web': 'Webentwicklung',
    'lab.services.web.desc': 'CMS, Landingpages, Funnels - maßgeschneiderte Weblösungen für Ihren Erfolg.',
    'lab.services.process': 'KI-gestützte Prozessautomatisierung',
    'lab.services.process.desc': 'Optimierung und Automatisierung von Geschäftsprozessen durch künstliche Intelligenz.',
    'lab.services.agents': 'KI-Agenten-Integration',
    'lab.services.agents.desc': 'Text, Mail, CRM - intelligente Agenten für automatisierte Kommunikation und Verwaltung.',
    'lab.services.forms': 'Formular- & Datenbank-Anbindungen',
    'lab.services.forms.desc': 'Nahtlose Integration von Notion, Airtable, Supabase und anderen Datenquellen.',
    'lab.services.tracking': 'Tracking- & Analyse-Setups',
    'lab.services.tracking.desc': 'GA4, Tag Manager, Pixel, Dashboards - umfassende Datenanalyse und Reporting.',
    'lab.agentHub.title': 'New Edge Agent Hub',
    'lab.agentHub.subtitle': 'Unsere eigenen KI-Anwendungen – sofort einsatzbereit für maximale Effizienz',
    'lab.workforce.title': 'KI-Helfer Workforce',
    'lab.workforce.description': '70+ spezialisierte KI-Agenten für Copywriting, HR, Marketing, Strategie und mehr.',
    'lab.workforce.lifetime': 'Lebenslanger Zugang ohne Abonnement.',
    'lab.workforce.features.noMonthlyCosts': 'Keine monatlichen Kosten',
    'lab.workforce.features.readyToUse': 'Sofort einsatzbereit',
    'lab.workforce.features.discount': '80% Rabatt für kurze Zeit',
    'lab.upcoming.smartAnalytics': 'Smart Analytics Agent',
    'lab.upcoming.smartAnalytics.desc': 'Automatisierte Datenanalyse und Erkenntnisgewinnung für datengetriebene Entscheidungen.',
    'lab.upcoming.creativeCopilot': 'Creative Copilot',
    'lab.upcoming.creativeCopilot.desc': 'KI-Assistent für kreative Prozesse und Content-Generierung.',
    'lab.upcoming.processOptimizer': 'Process Optimizer',
    'lab.upcoming.processOptimizer.desc': 'Intelligente Prozessautomatisierung für maximale Effizienz.',
    'lab.upcoming.predictiveInsights': 'Predictive Insights',
    'lab.upcoming.predictiveInsights.desc': 'Vorhersagemodelle für strategische Planung und Risikomanagement.',
    'lab.cta.title': 'Bereit für die Zukunft?',
    'lab.cta.description': 'Lassen Sie uns gemeinsam innovative Technologien erkunden und implementieren.',
    
    // Legal pages
    'legal.impressum.title': 'Impressum',
    'legal.privacy.title': 'Datenschutzerklärung',
    'legal.contact.title': 'Kontakt',
    'legal.backToHome': 'Zurück zur Startseite',
    
    // 404
    'notFound.title': '404',
    'notFound.subtitle': 'Oops! Seite nicht gefunden',
    'notFound.description': 'Die angeforderte Seite existiert nicht.',
    'notFound.backToHome': 'Zurück zur Startseite',
  },
  en: {
    // Navigation
    'nav.services': 'Services',
    'nav.media': 'Media',
    'nav.studio': 'Studio',
    'nav.lab': 'Lab',
    'nav.home': 'Home',
    'nav.contact': 'Contact',
    'nav.contactAction': 'Get in touch',
    
    // Common
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.contact': 'Contact',
    'common.backToHome': 'Back to Home',
    'common.discussProject': 'Discuss Project',
    'common.startProject': 'Start Project',
    'common.exploreServices': 'Explore Services',
    'common.requestProject': 'Request Project',
    'common.designProject': 'Start Design Project',
    'common.readyForNext': 'Ready for the next step?',
    'common.readyForFuture': 'Ready for the future?',
    'common.readyForDesign': 'Let´s design the edge',
    'common.readyForProject': 'Ready for your next project?',
    'common.readyForMedia': 'Ready for your media production?',
    'common.in48Hours': 'In 48 Hours',
    'common.available': 'AVAILABLE',
    'common.coming': 'Q4 2025',
    'common.ourServices': 'OUR SERVICES',
    'common.keyActivities': 'Key Activities',
    'common.projectServices': 'PROJECT-BASED SERVICES',
    'common.kiPowered': 'AI-POWERED SOLUTIONS',
    'common.featuredApps': 'Featured Applications',
    'common.upcomingApps': 'Upcoming Applications',
    'common.additionally': 'ADDITIONALLY',
    'common.inDevelopment': 'In active development',
    
    // Homepage
    'home.hero.brand': 'BRAND',
    'home.hero.intelligence': 'INTELLIGENCE',
    'home.hero.forDigitalAge': 'FOR THE DIGITAL AGE',
    'home.hero.title': 'New Edge',
    'home.hero.subtitle': 'One Team. Three Approaches. Infinite Possibilities.',
    'home.hero.description': 'We transform visions into digital realities through intelligent strategies, compelling content and innovative technologies.',
    'home.visual.strategy': 'STRATEGY',
    'home.visual.onPoint': 'ON-POINT',
    'home.visual.creative': 'CREATIVE TECH',
    'home.mission.title': 'Driving innovation through intelligent automation',
    'home.mission.description': 'With Media, Studio and Lab, we connect content, design and systems – for brands that function and grow.',
    'home.grow.title': 'We grow with our clients',
    'home.mission.card.title': 'OUR MISSION',
    'home.mission.card.description': 'With Media, Studio and Lab, we connect content, design and systems - for brands that function and grow.',
    'home.vision.card.title': 'OUR VISION',
    'home.vision.card.description': 'We shape a new generation of brands: automated, structured and visible.',
    'home.goal.card.title': 'OUR GOAL',
    'home.goal.card.description': 'Providing people and companies access to innovation for simpler and more effective processes.',
    'home.why.title': 'Why New Edge?',
    'home.usp1.title': 'Impact through automation',
    'home.usp1.description': 'Intelligent systems sustainably increase your efficiency',
    'home.usp2.title': 'Marketing expertise meets technical implementation',
    'home.usp2.description': 'Perfect symbiosis of strategy and innovation',
    'home.usp3.title': 'Focus on innovation and growth',
    'home.usp3.description': 'Future-oriented solutions for sustainable success',
    'home.services.title': 'Our Services',
    'home.contact.title': 'Ready to get started?',
    'home.contact.description': 'Let\'s talk about your next project and create something extraordinary together.',
    'home.contact.form.name': 'Name',
    'home.contact.form.email': 'Email',
    'home.contact.form.message': 'Message',
    'home.contact.form.send': 'Send Message',
    'home.contact.success.title': 'We design for you',
    'home.contact.success.message': 'Thank you for your inquiry! We will get back to you soon.',
    'home.contact.error.title': 'Error',
    'home.contact.error.message': 'There was a problem sending your message. Please try again.',
    
    // Services
    'services.hero.title': 'NEW EDGE SERVICES',
    'services.hero.journey': 'THE JOURNEY',
    'services.hero.fromVision': 'FROM VISION TO REALITY',
    'services.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'services.hero.description': 'We accompany you on a structured journey from the first idea to the final implementation.',
    'services.keyActivities': 'Key Activities',
    'services.yourPath': 'Your Path to Success',
    'services.strategy.title': 'Strategic Consulting',
    'services.strategy.description': 'Digital transformation and strategic consulting for sustainable business success.',
    'services.design.title': 'Creative Design',
    'services.design.description': 'Aesthetic solutions that bring your brand to life and inspire users.',
    'services.development.title': 'Tech Development',
    'services.development.description': 'State-of-the-art technology solutions for complex digital challenges.',
    'services.studio.tag': 'NEW EDGE STUDIO',
    'services.studio.tagline': 'Your ideas, our strategy',
    'services.studio.description': 'This is where it all begins. We develop the visual identity, strategy and foundation for your project.',
    'services.studio.button': 'Develop Strategy',
    'services.media.tag': 'NEW EDGE MEDIA',
    'services.media.tagline': 'The perfect stage for your brand',
    'services.media.description': 'Content production and reach. This is where everything is produced, published and controlled.',
    'services.media.button': 'Create Content',
    'services.lab.tag': 'NEW EDGE LAB',
    'services.lab.tagline': 'The perfect interface for strategy & technology',
    'services.lab.description': 'Backend, AI and technical implementation. This is where everything becomes intelligent and automated.',
    'services.lab.button': 'Implement Technology',
    'services.cta.title': 'Ready for your next project?',
    'services.cta.description': 'Let\'s develop innovative solutions together that advance your business.',
    
    // Media
    'media.hero.title': 'NEW EDGE MEDIA',
    'media.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'media.hero.revolution': 'CONTENT REVOLUTION',
    'media.hero.description': 'MEDIA produces, publishes and controls everything that becomes visible externally.',
    'media.hero.tagline': ' From strategy to viral implementation.',
    'media.services.operative': 'Operational Implementation',
    'media.services.operative.desc': 'Strategic content production and targeted reach for maximum visibility.',
    'media.services.content': 'Content Production & Reach',
    'media.services.content.desc': 'Professional content creation for maximum reach and engagement.',
    'media.services.marketing': 'Marketing & Visibility',
    'media.services.marketing.desc': 'Strategic campaigns for optimal performance marketing and launch campaigns.',
    'media.services.launch': 'Launch Campaigns & Performance Marketing',
    'media.services.launch.desc': 'Successful product launches and data-driven performance marketing.',
    'media.services.seo': 'SEO/SEA Implementation & Conversion Tracking',
    'media.services.seo.desc': 'Search engine optimization and content marketing with precise copywriting.',
    'media.services.copywriting': 'Content Marketing & Copywriting',
    'media.services.copywriting.desc': 'Strategic content marketing with compelling texts and messages.',
    'media.services.creative': 'Creative Content Production (Video, Visuals, Reels)',
    'media.services.creative.desc': 'High-quality video and visual production for all digital channels.',
    'media.services.newsletter': 'Newsletter, Ads & Campaign Distribution',
    'media.services.newsletter.desc': 'Professional newsletter campaigns and strategic advertising distribution.',
    'media.cta.title': 'Ready for the next step?',
    'media.cta.description': 'Let\'s revolutionize your content strategy together and build sustainable reach.',
    
    // Studio
    'studio.hero.title': 'NEW EDGE STUDIO',
    'studio.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'studio.hero.excellence': 'DESIGN EXCELLENCE',
    'studio.hero.description': 'STUDIO provides the foundation: Everything is strategically prepared, thought through and planned.',
    'studio.hero.tagline': ' For smooth implementation in MEDIA & LAB',
    'studio.services.foundations': 'Strategic foundations for your brand success',
    'studio.services.strategy': 'Strategy & Brand Identity',
    'studio.services.strategy.desc': 'Strategic brand positioning and target group analysis for clear orientation.',
    'studio.services.brand': 'Brand Story',
    'studio.services.brand.desc': 'Authentic brand stories with clear values and unique tonality.',
    'studio.services.competition': 'Competitive Analysis & Differentiation Strategy',
    'studio.services.competition.desc': 'Strategic market analysis and visual concept for clear differentiation.',
    'studio.services.moodboards': 'Moodboards & Key Visual Direction',
    'studio.services.moodboards.desc': 'Creative design and color worlds for a unified visual identity.',
    'studio.services.templates': 'Template Framework for Social Media & Print',
    'studio.services.templates.desc': 'Unified templates and digital structure with funnel logic.',
    'studio.services.wireframes': 'User Guidance & Funnel Wireframes',
    'studio.services.wireframes.desc': 'Conversion goals and strategic page structure for maximum effectiveness.',
    'studio.cta.title': 'Let´s design the edge',
    'studio.cta.description': 'Together we develop a design that brings your vision to life and inspires your target audience.',
    
    // Lab
    'lab.hero.title': 'NEW EDGE LAB',
    'lab.hero.subtitle': 'For strategy. aesthetics. & tech.',
    'lab.hero.innovation': 'TECH INNOVATION',
    'lab.hero.description': 'LAB turns ideas into real, functioning systems — secure, automated, efficient.',
    'lab.hero.tagline': '     Innovation through intelligent technology.',
    'lab.services.tech': 'Technical Implementation',
    'lab.services.requirements': 'Tailored solutions for your specific requirements',
    'lab.services.implementation': 'Technical Implementation',
    'lab.services.implementation.desc': 'Professional development and implementation of technical solutions for your company.',
    'lab.services.ai': 'AI Integration & Automation',
    'lab.services.ai.desc': 'Intelligent automation and AI integration into existing business processes.',
    'lab.services.backend': 'Backend & Tech Implementation',
    'lab.services.backend.desc': 'Robust backend systems and technical infrastructure for scalable applications.',
    'lab.services.web': 'Web Development',
    'lab.services.web.desc': 'CMS, landing pages, funnels - tailor-made web solutions for your success.',
    'lab.services.process': 'AI-powered Process Automation',
    'lab.services.process.desc': 'Optimization and automation of business processes through artificial intelligence.',
    'lab.services.agents': 'AI Agent Integration',
    'lab.services.agents.desc': 'Text, mail, CRM - intelligent agents for automated communication and management.',
    'lab.services.forms': 'Form & Database Connections',
    'lab.services.forms.desc': 'Seamless integration of Notion, Airtable, Supabase and other data sources.',
    'lab.services.tracking': 'Tracking & Analysis Setups',
    'lab.services.tracking.desc': 'GA4, Tag Manager, Pixel, Dashboards - comprehensive data analysis and reporting.',
    'lab.agentHub.title': 'New Edge Agent Hub',
    'lab.agentHub.subtitle': 'Our own AI applications – ready to use immediately for maximum efficiency',
    'lab.workforce.title': 'AI Helper Workforce',
    'lab.workforce.description': '70+ specialized AI agents for copywriting, HR, marketing, strategy and more.',
    'lab.workforce.lifetime': 'Lifetime access without subscription.',
    'lab.workforce.features.noMonthlyCosts': 'No monthly costs',
    'lab.workforce.features.readyToUse': 'Ready to use immediately',
    'lab.workforce.features.discount': '80% discount for a limited time',
    'lab.upcoming.smartAnalytics': 'Smart Analytics Agent',
    'lab.upcoming.smartAnalytics.desc': 'Automated data analysis and insight generation for data-driven decisions.',
    'lab.upcoming.creativeCopilot': 'Creative Copilot',
    'lab.upcoming.creativeCopilot.desc': 'AI assistant for creative processes and content generation.',
    'lab.upcoming.processOptimizer': 'Process Optimizer',
    'lab.upcoming.processOptimizer.desc': 'Intelligent process automation for maximum efficiency.',
    'lab.upcoming.predictiveInsights': 'Predictive Insights',
    'lab.upcoming.predictiveInsights.desc': 'Prediction models for strategic planning and risk management.',
    'lab.cta.title': 'Ready for the future?',
    'lab.cta.description': 'Let\'s explore and implement innovative technologies together.',
    
    // Legal pages
    'legal.impressum.title': 'Legal Notice',
    'legal.privacy.title': 'Privacy Policy',
    'legal.contact.title': 'Contact',
    'legal.backToHome': 'Back to Home',
    
    // Studio
    'studio.title': 'NEW EDGE STUDIO',
    'studio.subtitle': 'DESIGN EXCELLENCE',
    'studio.description': 'STUDIO provides the foundation: Everything is strategically prepared, considered and planned.',
    'studio.emphasis': 'For seamless implementation in MEDIA & LAB',
    'studio.startProject': 'Start project',
    'studio.ourServices': 'OUR SERVICES',
    'studio.servicesSubtitle': 'Strategic foundations for your brand success',
    'studio.strategy.title': 'Strategy & Brand Identity',
    'studio.strategy.desc': 'Strategic brand positioning and target audience analysis for clear direction.',
    'studio.brandStory.title': 'Brand Story',
    'studio.brandStory.desc': 'Authentic brand stories with clear values and unique tonality.',
    'studio.competitive.title': 'Competitive Analysis & Differentiation Strategy',
    'studio.competitive.desc': 'Strategic market analysis and visual concept for clear differentiation.',
    'studio.moodboards.title': 'Moodboards & Keyvisual Direction',
    'studio.moodboards.desc': 'Creative design and color worlds for a consistent visual identity.',
    'studio.templates.title': 'Template Framework for Social Media & Print',
    'studio.templates.desc': 'Consistent templates and digital structure with funnel logic.',
    'studio.userFlow.title': 'User Flow & Funnel Wireframes',
    'studio.userFlow.desc': 'Conversion goals and strategic page structure for maximum effectiveness.',
    'studio.ctaTitle': 'Let´s design the edge',
    'studio.ctaDescription': 'Together we develop a design that brings your vision to life and inspires your target audience.',
    'studio.ctaButton': 'Start design project',
    
    // Lab
    'lab.title': 'NEW EDGE LAB',
    'lab.subtitle': 'TECH INNOVATION',
    'lab.description': 'LAB turns ideas into real, functioning systems — secure, automated, efficient.',
    'lab.emphasis': 'Innovation through intelligent technology.',
    'lab.startProject': 'Start project',
    'lab.projectServices': 'PROJECT-BASED SERVICES',
    'lab.technicalImplementation': 'Technical Implementation',
    'lab.customSolutions': 'Customized solutions for your specific requirements',
    'lab.requestProject': 'Request project',
    'lab.additionally': 'ADDITIONALLY',
    'lab.kiPowered': 'AI-POWERED SOLUTIONS',
    'lab.agentHub': 'New Edge Agent Hub',
    'lab.agentHubDesc': 'Our own AI applications - ready to use for maximum efficiency',
    'lab.inDevelopment': 'In active development',
    'lab.available': 'AVAILABLE',
    'lab.helferWorkforce': 'AI Helper Workforce',
    'lab.helferDesc': '70+ specialized AI agents for copywriting, HR, marketing, strategy and more.',
    'lab.lifetimeAccess': 'Lifetime access without subscription.',
    'lab.noCosts': 'No monthly costs',
    'lab.readyToUse': 'Ready to use',
    'lab.discount': '80% discount for a limited time',
    'lab.inHours': 'In 48 hours',
    'lab.services.technical': 'Technical Implementation',
    'lab.services.technicalDesc': 'Professional development and implementation of technical solutions for your business.',
    'lab.services.aiIntegration': 'AI Integration & Automation',
    'lab.services.aiIntegrationDesc': 'Intelligent automation and AI integration into existing business processes.',
    'lab.services.backendTech': 'Backend & Tech Implementation',
    'lab.services.backendTechDesc': 'Robust backend systems and technical infrastructure for scalable applications.',
    'lab.services.webDev': 'Web Development',
    'lab.services.webDevDesc': 'CMS, landing pages, funnels - tailor-made web solutions for your success.',
    'lab.services.processAuto': 'AI-supported Process Automation',
    'lab.services.processAutoDesc': 'Optimization and automation of business processes through artificial intelligence.',
    'lab.services.agentIntegration': 'AI Agent Integration',
    'lab.services.agentIntegrationDesc': 'Text, mail, CRM - intelligent agents for automated communication and management.',
    'lab.services.formConnections': 'Form & Database Connections',
    'lab.services.formConnectionsDesc': 'Seamless integration of Notion, Airtable, Supabase and other data sources.',
    'lab.services.trackingAnalytics': 'Tracking & Analytics Setups',
    'lab.services.trackingAnalyticsDesc': 'GA4, Tag Manager, Pixel, Dashboards - comprehensive data analysis and reporting.',
    
    // Legal translations
    'legal.impressumPage': 'Legal Notice',
    'legal.privacyPage': 'Privacy Policy',
    'legal.legalInfo': 'Information according to § 5 TMG',
    'legal.responsiblePerson': 'Authorized representative: Responsible person on request',
    'legal.smallBusiness': 'This is a small business according to § 19 UStG – VAT is not shown.',
    'legal.responsibleProvider': 'Responsible Provider',
    'legal.responsibleText': 'Responsible for the processing of personal data within the meaning of the General Data Protection Regulation (GDPR) is:',
    'legal.dataCollection': 'Collection and Processing of Personal Data',
    'legal.dataCollectionText': 'Personal data is only processed by us when this is necessary for the provision of our website, for communication or for the implementation of advertising measures. Data is only passed on to third parties within the framework of legal provisions.',
    'legal.serverLogs': 'Server Log Files',
    'legal.serverLogsText': 'When visiting our website, the following data is automatically recorded by the hosting provider:',
    'legal.logData.ip': 'IP address',
    'legal.logData.dateTime': 'Date and time of access',
    'legal.logData.browser': 'Browser type and version',
    'legal.logData.os': 'Operating system',
    'legal.logData.referrer': 'Referrer URL',
    'legal.logPurpose': 'This data serves exclusively for technical security and error analysis. No merging with other data sources takes place.',
    'legal.contact': 'Contact',
    'legal.contactText': 'If you contact us by email or via a contact form, we store your information to process your request and for any follow-up questions. This data will not be passed on without your consent.',
    'legal.metaPixel': 'Use of Meta (Facebook) Pixel',
    'legal.metaPixelText1': 'We use the Meta Pixel on our website to track user behavior after clicking on an advertisement on Facebook or Instagram. This serves to analyze and optimize our campaigns.',
    'legal.metaPixelText2': 'The collected data is anonymous for us, but is processed by Meta and linked to your Meta profile if you are logged in there. You can find more information about this in Meta\'s privacy policy.',
    'legal.metaPixelOptOut': 'You can object to data collection by the Meta Pixel at any time - for example via the cookie settings on our website or directly with Meta.',
    'legal.cookies': 'Cookies',
    'legal.cookiesText': 'Our website uses cookies to provide basic functions and improve your user experience. You have the option to specify which cookies you want to allow via our cookie settings.',
    'legal.rights': 'Your Rights',
    'legal.rightsText': 'As a data subject, you have the following rights under GDPR at any time:',
    'legal.rightsList.info': 'Information about the data stored about you',
    'legal.rightsList.correction': 'Correction of incorrect data',
    'legal.rightsList.deletion': 'Deletion of your data (right to be forgotten)',
    'legal.rightsList.restriction': 'Restriction of processing',
    'legal.rightsList.objection': 'Objection to processing',
    'legal.rightsList.portability': 'Data portability',
    'legal.rightsContact': 'Please send your request by email to:',
    'legal.changes': 'Changes to this Privacy Policy',
    'legal.changesText': 'We reserve the right to adapt this privacy policy if changes to our website or legal requirements make this necessary. You can always find the current version on this page.',
    
    // 404
    'notFound.title': '404',
    'notFound.subtitle': 'Oops! Page not found',
    'notFound.description': 'The requested page does not exist.',
    'notFound.backToHome': 'Back to Home',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'de';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};