// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbvnoonyfsuedneholtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idm5vb255ZnN1ZWRuZWhvbHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjYwMTksImV4cCI6MjA2ODYwMjAxOX0.8lqUNTYC7yPB2SwPBkiFLzSjjPfoHQulUn55CHeTZRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});